### ISSUE TITLE
does OM-server support multiple instances

### ISSUE THREAD

**Issue by seefan** [AdTiming/OpenMediation#1]
OM-Server is responsible for SDK access and mediation logic processing. Can I deploy multiple instances of OM-server to serve app users in different regions of the world?

**Comment by OpenMediationProject** [comment]
Yes, you can add more OM-server instances when load increases. As a matter of fact, it's highly recommended to deploy it in an auto-scaling group together with a load balancer to automatically respond to load changes and provide high availability.

Also, you can deploy one OM-server group in each region to best serve your mobile users in different part of the world.

**Comment by seefan** [comment]
When deploying multiple OM-server groups in different regions, do I need to modify the DB  or any config files? And how to make the SDK access the right group?

**Comment by OpenMediationProject** [comment]
No, you don't need to modify anything on your part. It is automatically done. You can use ways like geoproximity routing to route your traffic in a particular geolocation to your designated group.
