### ISSUE TITLE
custom timezone other than UTC

### ISSUE THREAD

**Issue by zigzed** [AdTiming/OpenMediation#2]
The time zone in the current project is fixed at UTC. The Dashboard data also shows UTC time. Can the custom time zone be supported in the future?

**Comment by OpenMediationProject** [comment]
The project currently limits the time zone to UTC, taking into account the time zone requirements for compatibility with all adnetworks. It needs to pull revenue data from adnetworks, and the time zone supported by each adnetwork is not the same. Only UTC is universally supported. And besides some adnetworks only provide daily data that cannot convert between different time zones. Therefore the current UTC limit can ensure that all data is consistent and error-free.
